[2017-08-15 16:36:13,414] ERROR Securitisation.Utilities.Common.Log4NetLogService - Create session failed
System.IO.FileNotFoundException: Could not find file 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'.
File name: 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at TaskProcessEngine.SessionManagementService.CreateSessionByTaskCode(String applicationDomain, String sessionVariable, String taskCode) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\SessionManagementService.svc.cs:line 120
[2017-08-15 16:36:19,075] ERROR Securitisation.Utilities.Common.Log4NetLogService - Create session failed
System.IO.FileNotFoundException: Could not find file 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'.
File name: 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at TaskProcessEngine.SessionManagementService.CreateSessionByTaskCode(String applicationDomain, String sessionVariable, String taskCode) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\SessionManagementService.svc.cs:line 120
[2017-08-15 16:47:53,548] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 61b7dd79-4ca1-48fd-85b0-62f707eae360 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Cannot open database "DAL_SEC" requested by the login. The login failed.
Login failed for user 'CD17D-6165-SYW\Administrator'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-15 16:49:13,345] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0da3f798-8dec-4271-b041-4ac39f31c961 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_133.dbo.tblFactLoan'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-15 16:49:54,315] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0da3f798-8dec-4271-b041-4ac39f31c961 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_132.dbo.tblFactLoan'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-15 16:50:02,539] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 16e035e5-dd44-437f-bfae-1636e7e63ef9 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_132.dbo.tblFactLoan'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-15 16:51:00,118] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 20b8e7b6-bb65-4d97-824c-f23ea41ee128 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_132.dbo.tblFactLoan'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-15 16:58:35,809] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 20b8e7b6-bb65-4d97-824c-f23ea41ee128 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_132.dbo.tblFactLoan'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
